# deploy.ps1 - NeosTech RFID System v6.0
param([switch]$OnlyTest,[switch]$SkipGateway,[switch]$SkipDashboard,[switch]$SkipCloudFunction)
$ErrorActionPreference="Continue"
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host "DEPLOYMENT - NEOS TECH RFID SYSTEM v6.0" -ForegroundColor Cyan
Write-Host "Fecha: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host "`n[FASE 0] Verificando prerequisitos..." -ForegroundColor Yellow
$tools=@{}
$tools["Firebase"]=(Get-Command firebase -EA SilentlyContinue)-ne$null
$tools[".NET"]=(Get-Command dotnet -EA SilentlyContinue)-ne$null
$tools["gcloud"]=(Get-Command gcloud -EA SilentlyContinue)-ne$null
$tools["Python"]=(Get-Command python -EA SilentlyContinue)-ne$null
foreach($t in $tools.GetEnumerator()){if($t.Value){Write-Host "  + $($t.Key)" -ForegroundColor Green}else{Write-Host "  - $($t.Key) NO INSTALADO" -ForegroundColor Red}}
if(-not$SkipGateway){Write-Host "`n[FASE 1] Compilando Gateway..." -ForegroundColor Yellow;$gp="src\Gateway\Rfid_gateway.csproj";if(Test-Path $gp){Write-Host "  + Proyecto encontrado" -ForegroundColor Green;if(-not$OnlyTest){dotnet clean $gp -c Release --verbosity quiet;dotnet publish $gp -c Release -o "dist\gateway" --verbosity quiet;if($LASTEXITCODE -eq 0){Write-Host "  + Compilacion exitosa -> dist\gateway\" -ForegroundColor Green;if(Test-Path "src\Gateway\gateway.config.json"){Copy-Item "src\Gateway\gateway.config.json" -Destination "dist\gateway\" -Force;Write-Host "    Config copiado" -ForegroundColor DarkGray}}else{Write-Host "  - Error compilando" -ForegroundColor Red}}}else{Write-Host "  - Proyecto NO encontrado" -ForegroundColor Red}}
if(-not$SkipDashboard){Write-Host "`n[FASE 2] Verificando Dashboard..." -ForegroundColor Yellow;$ok=$true;@("src\web\index.html","src\web\firebase-config.js","src\web\style.css")|%{if(Test-Path $_){$s=[math]::Round((gi $_).Length/1024,1);Write-Host "  + $(Split-Path $_ -Leaf) - $s KB" -ForegroundColor Green}else{Write-Host "  - $(Split-Path $_ -Leaf) NO ENCONTRADO" -ForegroundColor Red;$ok=$false}};if(Test-Path "firebase.json"){Write-Host "  + firebase.json OK" -ForegroundColor Green}else{Write-Host "  - firebase.json NO ENCONTRADO" -ForegroundColor Red}}
if(-not$SkipCloudFunction){Write-Host "`n[FASE 3] Verificando Cloud Function..." -ForegroundColor Yellow;if(Test-Path "src\functions\main.py"){Write-Host "  + main.py OK" -ForegroundColor Green}else{Write-Host "  - main.py NO ENCONTRADO" -ForegroundColor Red};if(Test-Path "src\functions\requirements.txt"){Write-Host "  + requirements.txt OK" -ForegroundColor Green}else{Write-Host "  - requirements.txt NO ENCONTRADO" -ForegroundColor Red}}
Write-Host "`n[FASE 4] Verificando Firestore Rules..." -ForegroundColor Yellow;$rp="firestore.rules";if(-not(Test-Path $rp)){$rp="config\firestore.rules"};if(Test-Path $rp){Write-Host "  + Firestore Rules OK" -ForegroundColor Green}else{Write-Host "  - Firestore Rules NO ENCONTRADAS" -ForegroundColor Red}
Write-Host "`n[FASE 5] Verificando Configuraciones..." -ForegroundColor Yellow;if(Test-Path "src\Gateway\gateway.config.json"){$gc=Get-Content "src\Gateway\gateway.config.json"|ConvertFrom-Json;Write-Host "  + Gateway Config:" -ForegroundColor Green;Write-Host "    Client: $($gc.client_id)" -ForegroundColor DarkGray;Write-Host "    Puerto: $($gc.server.port)" -ForegroundColor DarkGray;Write-Host "    Access Points: $($gc.access_points.Count)" -ForegroundColor DarkGray;$gc.access_points|%{Write-Host "      - $($_.name): $($_.reader_ip):$($_.reader_port)" -ForegroundColor DarkGray}}
if(-not$OnlyTest){Write-Host "`n[FASE 6] DEPLOYMENT..." -ForegroundColor Yellow;if(-not$SkipDashboard-and$tools["Firebase"]){Write-Host "`n  Desplegando Dashboard..." -ForegroundColor Cyan;firebase deploy --only hosting;if($LASTEXITCODE -eq 0){Write-Host "  + Dashboard OK -> https://neos-tech.web.app" -ForegroundColor Green}};if($tools["Firebase"]){Write-Host "`n  Desplegando Firestore Rules..." -ForegroundColor Cyan;firebase deploy --only firestore:rules};if(-not$SkipCloudFunction-and$tools["gcloud"]){Write-Host "`n  Desplegando Cloud Function..." -ForegroundColor Cyan;$cl=Get-Location;Set-Location "src\functions";gcloud functions deploy rfid-gateway --runtime python39 --trigger-http --allow-unauthenticated --entry-point process_tag --region us-central1 --project neos-tech;Set-Location $cl};Write-Host "`n[FASE 7] Verificacion..." -ForegroundColor Yellow;Start-Sleep -Seconds 5;try{$r=Invoke-WebRequest -Uri "https://neos-tech.web.app" -UseBasicParsing -TimeoutSec 10;if($r.StatusCode -eq 200){Write-Host "  + Dashboard accesible" -ForegroundColor Green}}catch{Write-Host "  ! Dashboard aun cargando" -ForegroundColor Yellow};try{$gw=Invoke-RestMethod -Uri "http://localhost:60000/health" -TimeoutSec 3;Write-Host "  + Gateway Local OK - $($gw.client_id)" -ForegroundColor Green}catch{Write-Host "  ! Gateway Local no iniciado" -ForegroundColor Gray}}
Write-Host "`n=====================================================" -ForegroundColor Green;if($OnlyTest){Write-Host "VERIFICACION COMPLETADA" -ForegroundColor Green}else{Write-Host "DEPLOYMENT COMPLETADO" -ForegroundColor Green};Write-Host "=====================================================" -ForegroundColor Green
if(-not$OnlyTest){Write-Host "`nURLs:" -ForegroundColor Cyan;Write-Host "  Dashboard: https://neos-tech.web.app" -ForegroundColor White;Write-Host "  Gateway: http://localhost:60000" -ForegroundColor White;Write-Host "`nCredenciales:" -ForegroundColor Cyan;Write-Host "  admin/admin123 | guardia/guardia123" -ForegroundColor White}
Write-Host "`nListo!" -ForegroundColor Green
